version: "2"
services:
  node1:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/andrea/Documents/University/Didattica/RC2018/docker/2.Node:/home/node/app
    ports:
      - "8081:8081"
    expose:
      - 8081
    command: "npm start"
  node2:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /home/andrea/Documents/University/Didattica/RC2018/docker/2.Node:/home/node/app
    ports:
      - "8082:8081"
    expose:
      - 8081
    command: "npm start"
