version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node
    expose:
      - "8089"
    command: "npm start"
